### ISSUE TITLE
Unit test error on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by brandonaaron** [lovell/attention#1]
I'm seeing two unit test failures on Mac OS X 10.10.5. Line [44 and 45](https://github.com/lovell/attention/blob/master/test/unit.js#L44-L45) values are just slightly off. I'm seeing `59` for line 44 and `#60493b` for line 45.

Side note... malloc.h is stored elsewhere on the mac. I copied malloc.h from /usr/include/malloc/malloc.h to just /usr/include/malloc.h so that it could be found.

**Comment by lovell** [comment]
Hi Brandon, I don't think I've ever tried compiling this module on a Mac, thanks for being the first to try!

We could add `/usr/include/malloc` to the [include_dirs](https://github.com/lovell/attention/blob/master/binding.gyp#L19) directive to get round the malloc vs stdlib problem.

As for the slightly-off values, I wonder if there's a platform-specific rounding error/difference in there somewhere.

**Comment by brandonaaron** [comment]
I was also assuming there might be some platform-specific rounding error/difference related to those unit test failures as well. Not entirely sure how best to handle that scenario. I'm not entirely familiar with the underlying functions yet either. Is this potentially something that needs to be solved in exoquant?

Submitted a [pull request](#2) for the include dirs addition. Tested locally and it worked great.

**Comment by lovell** [comment]
My best guess is the presence of the [-Ofast](https://github.com/lovell/attention/blob/master/binding.gyp#L46) compile-time flag. Amongst other things it enables "fast-math" to make floating-point calculations less strict.

The results are close enough for the purposes of this module so I think the solution here is have the tests expect results within a (narrow) range.

**Comment by lovell** [comment]
Thanks for sorting the tests. I'll modify the Travis CI config to compile+test via clang/llvm as well as gcc.
