### ISSUE TITLE
Region not found?

### ISSUE THREAD

**Issue by homerjam** [lovell/attention#10]
Hi Lovell,

I realise that `attention` is using libvips and image analysis is very tricky anyway but thought I'd post an image that seems to be troublesome in case it provides a useful test case. Specifically when trying to obtain a region it returns blank (empty object) and when getting a point it returns a somewhat unexpected (incorrect) result.

![test1](https://cloud.githubusercontent.com/assets/1055769/12884630/7de43be6-ce57-11e5-965d-0986f123346a.jpg)

(image © Karina Twiss 2016)

Thanks

**Comment by lovell** [comment]
Hi James, thanks for this superior test image. Is it OK to publicly post derivatives (namely [saliency masks](https://github.com/lovell/attention#salient-region)) of this work here for testing purposes?

The `Could not determine salient region` error it generates means there was no overlap of the two saliency masks. The improvements to edge detection suggested by John in #7 will help here.

If the salient region can't be found then the focal point will be meaningless. The `point` feature should probably return a consistent error when this occurs.

**Comment by homerjam** [comment]
Hi Lovell, yes it should be fine to use/post this image for testing purposes.

The changes in #7 sound good, looking forward to them being included.

And yes - an error from the `point` method would definitely be useful.

Thanks

**Comment by lovell** [comment]
So I've done a little tinkering, initially with the edge detection, which then allowed me to remove some of the relatively slow blurring operations also.

Edge/Sobel mask:
![](https://cloud.githubusercontent.com/assets/210965/13126589/fa839242-d5c2-11e5-8352-4a73ee4f5f34.jpg)

Contrast/colour-distance mask:
![](https://cloud.githubusercontent.com/assets/210965/13126592/fcba35b6-d5c2-11e5-8adc-ac94e739753c.jpg)

Combined mask:
![](https://cloud.githubusercontent.com/assets/210965/13126595/024c113e-d5c3-11e5-9ff2-0f5e203eefbb.jpg)

Result (extracted by sharp, natch):
![](https://cloud.githubusercontent.com/assets/210965/13126599/07ab435c-d5c3-11e5-8bf6-b811827eee69.jpg)

I still need to run this over the [MSRA](http://research.microsoft.com/en-us/um/people/jiansun/salientobject/salient_object.htm) images to fine-tune thresholds, but looking much better already.

**Comment by homerjam** [comment]
Yep, looking good. So just to confirm my understanding - would the `point` of this image be the centre of the region?

As an aside - have you ever looked into [opencv](https://github.com/Itseez/opencv) for face recognition?

**Comment by lovell** [comment]
> "would the point of this image be the centre of the region?"

The `point` is the weighted centre of all pixels in the combined mask, so almost. In this case it'll be near the inside of the model's left eye.

> "have you ever looked into opencv for face recognition?"

Yes, not recently but I experimented with it a few years ago. It uses a classifier (Haar?), a more complex technique than simple image processing. This will almost certainly provide better results if you know there is a face in the image and that the face is what is to be considered "salient".

**Comment by lovell** [comment]
I've created #11 to experiment with how effective detection of skin tone might be.

**Comment by homerjam** [comment]
Awesome. Thanks for clarifying.
