### ISSUE TITLE
Experiment with a skin tone mask

### ISSUE THREAD

**Issue by lovell** [lovell/attention#11]
Build range of skin tones:
- Scrape http://humanae.tumblr.com/ (via [API](https://www.tumblr.com/docs/en/api/v2)?) for all the top-left pixel values
- Convert to LAB
- Discard L channel
- Histogram the A and B channels

Build mask for an input image:
- Convert input image to LAB (already occurs when building the colour mask)
- Discard L channel
- Threshold A and B channel using min/max from above
- If num of pixels remaining >TBD%, use instead of colour mask

**Comment by homerjam** [comment]
This sounds very, very cool.

**Comment by homerjam** [comment]
What about using the LAB/hex code etc from the Pantone references? I can have a crack at getting those?

**Comment by lovell** [comment]
@homerjam Thanks for the offer. The infinite scroll suggests there are a lot of images and it looks like new entries are still being added. It should be quicker to automate this, and with much less damage to your sanity! :)

**Comment by lovell** [comment]
This forms part of the improved "attention" crop strategy in sharp v0.16.1+ http://sharp.dimens.io/en/stable/changelog/#v0161-13th-october-2016
