### ISSUE TITLE
Stream support

### ISSUE THREAD

**Issue by niftylettuce** [lovell/attention#13]

**Comment by niftylettuce** [comment]
As similar to <https://github.com/lovell/sharp/blob/af9d09f8ae7cd15ecb389bc9fd2b35adc78d79f7/index.js> can you add stream support?

**Comment by lovell** [comment]
Hello, I plan to merge an updated version of the "attention" algorithm into sharp. Follow https://github.com/lovell/sharp/issues/295 for updates. Do you think this will provide what you need?

**Comment by niftylettuce** [comment]
Yea that would be great, thank you.

**Comment by lovell** [comment]
In the meantime, sharp currently has an entropy-based [crop](http://sharp.dimens.io/en/stable/api/#cropoption) "strategy" you can use right now that provides a similar, if not quite as accurate, feature:
```javascript
const thumbnailer = sharp()
  .resize(200, 200)
  .crop(sharp.strategy.entropy);
readable
  .pipe(thumbnailer)
  .pipe(writable);
```
