### ISSUE TITLE
Accuracy test errors

### ISSUE THREAD

**Issue by brandonaaron** [lovell/attention#3]
I haven't really looked into this one at all. When running `npm run-script accuracy`, I'm getting two errors:
* `Error: Expecting 5000 images, found 2799`
* `Error: Cannot find module './userData.json'`

It does seem to download successfully and expand the data. Perhaps the downloads have changed?

Edit: This is on Mac OS X 10.10.5 and Node 4.1.1

**Comment by lovell** [comment]
I spy an extra line with what looks like not-very-accurate image dimensions in the UserDataB.zip files. I'm sure that script used to work fine ~9 months ago :)

Commit 42d098d skips this and seems to have fixed the errors.

If you're interested, you can modify the percentage values at https://github.com/lovell/attention/blob/master/src/mask.cc#L31 and https://github.com/lovell/attention/blob/master/src/mask.cc#L54 to see how it alters the accuracy outcomes.
