### ISSUE TITLE
Make edge detection symmetrical to improve mask overlap

### ISSUE THREAD

**Issue by jcupitt** [lovell/attention#7]
Not important at all, but you could change this code:

``` C++
  // Create horizontal operator
  vips::VImage sobelX = vips::VImage::new_matrixv(3, 3,
    -1.0, 0.0, 1.0,
    -2.0, 0.0, 2.0,
    -1.0, 0.0, 1.0);
  // Create vertical operator
  vips::VImage sobelY = vips::VImage::new_matrixv(3, 3,
    1.0, 2.0, 1.0,
    0.0, 0.0, 0.0,
    -1.0, -2.0, -1.0);

  // Apply Sobel operators
  vips::VImage sobelFiltered = grey.conv(sobelX) + grey.conv(sobelY);
```

to be:

``` C++
  vips::VImage sobel = vips::VImage::new_matrixv(3, 3,
    -1.0, 0.0, 1.0,
    -2.0, 0.0, 2.0,
    -1.0, 0.0, 1.0);
  vips::VImage sobelFiltered = grey.conv(sobel) + grey.conv(sobel.rot90());
```

It seems a little clearer to me. Sobel is also often defined as:

```
  vips::VImage sobelFiltered = (grey.conv(sobel) - 128).abs() + grey.conv(sobel.rot90()) - 128).abs();
```

So the sum of the absolute response. This way you detect positive and negative going edges, and it's symmetrical.

**Comment by lovell** [comment]
Great, thanks John. Your suggestion to use `abs()` should improve the overlap with the distance-from-average mask (with thresholds reduced accordingly).

If you've not already seen it, there's been some recent interest in adding this sort of feature to sharp e.g. https://github.com/lovell/sharp/issues/295

I'll probably fold some of this work into sharp after it's migrated to the new C++ bindings.

**Comment by lovell** [comment]
This suggestion made its way into the sharp-based implementation, thank you. https://github.com/lovell/sharp/blob/18b9991fe7bf22852a6e3b56f03d026a971bad48/src/operations.cc#L314
