### ISSUE TITLE
Trouble installing / new version required?

### ISSUE THREAD

**Issue by homerjam** [lovell/attention#9]
Hi Lovell

I'm having trouble installing this module on OSX, when I run `npm install attention` I get:

```
> attention@0.1.0 install /Users/jameshomer/Documents/projects/ace-assist/node_modules/attention
> node-gyp rebuild

  CC(target) Release/obj.target/attention/src/exoquant/exoquant.o
../src/exoquant/exoquant.c:26:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.
make: *** [Release/obj.target/attention/src/exoquant/exoquant.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

It looks like this was addressed with #2 however I don't think that has been published to npm.

When I try `npm install lovell/attention` I get:

```
> attention@0.1.0 install /Users/jameshomer/Documents/projects/ace-assist/node_modules/attention
> node-gyp rebuild

make: *** No rule to make target `Release/obj.target/attention/src/exoquant/exoquant.o', needed by `Release/attention.node'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

Which I think maybe because `exoquant.o` doesn't exist. Possibly this is because `exoquant` is a submodule and isn't actaully updated/installed when installing from github (possible link to #6)?

Any help appreciated!

**Comment by homerjam** [comment]
Update:

It looks like the submodule is the issue as I've managed to install with

```
npm i -S brandonaaron/attention#unsubmodule

**Comment by lovell** [comment]
I'll publish all the latest fixes to npm, probably later this evening, so you don't need to mess around with submodules. Thanks for the prompt.

**Comment by lovell** [comment]
v0.1.1 now available via npm

**Comment by homerjam** [comment]
Great, thanks. Thats sorted the problem.
